name: Run Bot OMIP

on:
  workflow_dispatch: # Botão manual "Run workflow"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Garante a instalação limpa da biblioteca de internet para o robô funcionar
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Executa o script.py e impede que erros internos do Python quebrem o GitHub
      - name: Executar o Script
        run: python script.py || echo "Script executado com aviso controlado."

      # Guarda o histórico no GitHub sem falhar se não houver alterações
      - name: Guardar Histórico Atualizado
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add historico_omip.json || true
          
          if git diff --staged --quiet; then
            echo "💤 Nada para atualizar no repositório."
          else
            git commit -m "💾 [Bot] Histórico atualizado [skip ci]"
            git push
            echo "💾 Histórico guardado com sucesso!"
          fi
